package modelo.entidad;
// Generated Jun 23, 2025 6:06:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Area generated by hbm2java
 */
public class Area  implements java.io.Serializable {


     private Integer idArea;
     private String nombre;
     private Set<Inventarios> inventarioses = new HashSet<Inventarios>(0);

    public Area() {
    }

	
    public Area(String nombre) {
        this.nombre = nombre;
    }
    public Area(String nombre, Set<Inventarios> inventarioses) {
       this.nombre = nombre;
       this.inventarioses = inventarioses;
    }
   
    public Integer getIdArea() {
        return this.idArea;
    }
    
    public void setIdArea(Integer idArea) {
        this.idArea = idArea;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Inventarios> getInventarioses() {
        return this.inventarioses;
    }
    
    public void setInventarioses(Set<Inventarios> inventarioses) {
        this.inventarioses = inventarioses;
    }




}


