package modelo.entidad;
// Generated Jun 23, 2025 6:06:54 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Inventarios generated by hbm2java
 */
public class Inventarios  implements java.io.Serializable {


     private Integer idInventarios;
     private Area area;
     private Usuarios usuarios;
     private Date fecha;
     private String nombreProducto;
     private Double cantidad;
     private Double peso;
     private Double precio;

    public Inventarios() {
        area= new Area();
        usuarios = new Usuarios();
    }

	
    public Inventarios(Date fecha, String nombreProducto) {
        this.fecha = fecha;
        this.nombreProducto = nombreProducto;
    }
    public Inventarios(Area area, Usuarios usuarios, Date fecha, String nombreProducto, Double cantidad, Double peso, Double precio) {
       this.area = area;
       this.usuarios = usuarios;
       this.fecha = fecha;
       this.nombreProducto = nombreProducto;
       this.cantidad = cantidad;
       this.peso = peso;
       this.precio = precio;
    }
   
    public Integer getIdInventarios() {
        return this.idInventarios;
    }
    
    public void setIdInventarios(Integer idInventarios) {
        this.idInventarios = idInventarios;
    }
    public Area getArea() {
        return this.area;
    }
    
    public void setArea(Area area) {
        this.area = area;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }
    public Double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Double cantidad) {
        this.cantidad = cantidad;
    }
    public Double getPeso() {
        return this.peso;
    }
    
    public void setPeso(Double peso) {
        this.peso = peso;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }




}


