package modelo.entidad;
// Generated Jun 23, 2025 6:06:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer idUsuarios;
     private String usuario;
     private String clave;
     private String nombre;
     private String correo;
     private String telefono;
     private String rol;
     private Set<Inventarios> inventarioses = new HashSet<Inventarios>(0);

    public Usuarios() {
    }

	
    public Usuarios(String usuario, String clave) {
        this.usuario = usuario;
        this.clave = clave;
    }
    public Usuarios(String usuario, String clave, String nombre, String correo, String telefono, String rol, Set<Inventarios> inventarioses) {
       this.usuario = usuario;
       this.clave = clave;
       this.nombre = nombre;
       this.correo = correo;
       this.telefono = telefono;
       this.rol = rol;
       this.inventarioses = inventarioses;
    }
   
    public Integer getIdUsuarios() {
        return this.idUsuarios;
    }
    
    public void setIdUsuarios(Integer idUsuarios) {
        this.idUsuarios = idUsuarios;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public Set<Inventarios> getInventarioses() {
        return this.inventarioses;
    }
    
    public void setInventarioses(Set<Inventarios> inventarioses) {
        this.inventarioses = inventarioses;
    }




}


